
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static org.jooq.impl.DSL.table;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author suresh
 */
public class TicketReport extends javax.swing.JInternalFrame {

    /**
     * Creates new form TicketReport
     */
    public TicketReport() {
        initComponents();
        loadout();
       
        
   
    
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight id", "Flightname", "Arrival", "Departure", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Connection con;
        PreparedStatement pre;
        int cc;

    public void loadout(){
           try {
               try {
                   Class.forName("con.mysql.jdbc.Driver");
               } catch (ClassNotFoundException ex) {
                   Logger.getLogger(BookTickets.class.getName()).log(Level.SEVERE, null, ex);
               }
               
               
               
               con  = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/airlinemanagement","root","suresh");
               java.sql.Statement s = con.createStatement();
               pre = con.prepareStatement("select * from flights ");
             
               ResultSet rs = pre.executeQuery();
               ResultSetMetaData RSMD = rs.getMetaData();
               cc = RSMD.getColumnCount();
               DefaultTableModel DFT = (DefaultTableModel)jTable1.getModel();
               DFT.setRowCount(0);
               while(rs.next()){
                   Vector v2 = new Vector();
                   for(int i = 1;i<=cc;i++){
                       v2.add(rs.getString("idFlights"));
                       v2.add(rs.getString("FlightName"));
                       v2.add(rs.getString("Arrival"));
                       v2.add(rs.getString("Departure"));
                       v2.add(rs.getString("Date"));
                   }
                   DFT.addRow(v2);
                   
                   
               }
           } catch (SQLException ex) {
                Logger.getLogger(TicketReport.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
   
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}

